
-- PASS 테이블 생성
CREATE TABLE PASS
(
    NO         	NUMBER(5)     PRIMARY KEY
  , NAME       	VARCHAR2(20) NOT NULL
  , DESCRIPTION VARCHAR2(1000) 
  , PRICE		NUMBER(7)	NOT NULL
  , DURATION	NUMBER(3)   NOT NULL
  , TOTAL_CLASSES  NUMBER(5) NOT NULL
);
-- PASS SEQ 생성
CREATE SEQUENCE SEQ_PASS_NO nocache;


-- TEACHER 테이블 생성
CREATE TABLE TEACHER
(
    ID         VARCHAR2(20)     PRIMARY KEY
  , NAME       VARCHAR2(20) NOT NULL
  , GENDER     CHAR(1) NOT NULL
  , PHONE		VARCHAR2(12)	NOT NULL UNIQUE
  , BIRTH_DATE  DATE	NOT NULL
  , REG_DATE	DATE DEFAULT SYSDATE
);

-- PAYMENT 테이블 생성
CREATE TABLE PAYMENT 
(
	NO			NUMBER(10)	PRIMARY KEY
  , MEMBER_ID	VARCHAR2(20) NOT NULL
  , PASS_NO		NUMBER(5)   NOT NULL
  , AMOUNT		NUMBER(7)  NOT NULL
  , PAY_METHOD		CHAR(4) NOT NULL-- 'CASH', 'CARD' 
  , PAY_DATE		DATE 	DEFAULT SYSDATE
  
    , CONSTRAINT FK_PAYMENT_PASS_NO FOREIGN KEY (PASS_NO)
    REFERENCES PASS(NO) ON DELETE CASCADE
);

-- PAYMENT SEQ 생성
CREATE SEQUENCE SEQ_PAYMENT_NO nocache;

-- REFUND 테이블 생성
CREATE TABLE REFUND
(
	NO		NUMBER(10) PRIMARY KEY
  , PAYMENT_NO NUMBER(10) NOT NULL
  , AMOUNT NUMBER(7) NOT NULL
  , REFUND_DATE DATE DEFAULT SYSDATE
  , REASON VARCHAR2(50)
  , STATUS CHAR(1) DEFAULT 'W' -- W, A, C
  
   , CONSTRAINT FK_REFUND_PAYMENT_NO FOREIGN KEY (PAYMENT_NO)
    REFERENCES PAYMENT(NO) ON DELETE CASCADE
);
-- REFUND SEQ 생성
CREATE SEQUENCE SEQ_REFUND_NO nocache;

--RESERVATION 테이블 생성
CREATE TABLE RESERVATION
(
	NO           NUMBER(10)     PRIMARY KEY
  , MEMBER_ID    VARCHAR2(20)   NOT NULL
  , STATUS       CHAR(1)        DEFAULT 'A' --'A', 'C', 'D' 
  , RESERVE_DATE DATE           NOT NULL
  , DETAIL       VARCHAR2(4000)
  , REG_DATE     DATE           DEFAULT SYSDATE  
);
-- RESERVATION SEQ 생성
CREATE SEQUENCE SEQ_RESERVATION_NO nocache;

-- SUBSCRIPTION 테이블 생성
CREATE TABLE SUBSCRIPTION
(
	NO NUMBER(10) PRIMARY KEY
  , PAYMENT_NO NUMBER(10) NOT NULL
  , MEMBER_ID	VARCHAR2(20) NOT NULL
  , PASS_NO NUMBER(10) NOT NULL
  , START_DATE	DATE NOT NULL
  , END_DATE	DATE NOT NULL
  , REMAIN_CLASSES NUMBER(5)
  
   , CONSTRAINT FK_SUBSCRIPTION_PAYMENT_NO FOREIGN KEY (PAYMENT_NO)
    REFERENCES PAYMENT(NO) ON DELETE CASCADE
     , CONSTRAINT FK_SUBSCRIPTION_PASS_NO FOREIGN KEY (PASS_NO)
    REFERENCES PASS(NO) ON DELETE CASCADE
);
--SUBSCRIPTION SEQ 생성
CREATE SEQUENCE SEQ_SUBSCRIPTION_NO nocache;


-- CLASS
CREATE TABLE CLASS 
(
	NO	NUMBER(10) PRIMARY KEY
  , TEACHER_ID VARCHAR2(20) NOT NULL
  , DOG_NO	NUMBER(10) NOT NULL
  , SUBSCRIPTION_NO NUMBER(10) NOT NULL
  , CLASS_DATE DATE NOT NULL
  , STATUS CHAR(1) DEFAULT 'A' --'A', 'C', 'D'
  , ATTENDANCE CHAR(1) -- 'P', 'A'
  , REG_DATE DATE DEFAULT SYSDATE
   , CONSTRAINT FK_CLASS_TEACHER_ID FOREIGN KEY (TEACHER_ID)
    REFERENCES TEACHER(ID) ON DELETE CASCADE
     , CONSTRAINT FK_CLASS_SUBSCRIPTION_NO FOREIGN KEY (SUBSCRIPTION_NO)
    REFERENCES SUBSCRIPTION(NO) ON DELETE CASCADE
);
-- CLASS SEQ 생성
CREATE SEQUENCE SEQ_CLASS_NO nocache;

-- ACTIVITY 테이블 생성
CREATE TABLE ACTIVITY
(
	NO NUMBER(10) PRIMARY KEY
  , DOG_NO NUMBER(10) NOT NULL
  , TEACHER_ID VARCHAR2(20) NOT NULL
  , ACTIVITY_DATE DATE NOT NULL
  , CONTENT VARCHAR2(4000)
  , IMG_ORI_NAME VARCHAR2(50)
  , IMG_SAVE_NAME VARCHAR2(50)
  , IMG_SIZE NUMBER(10)
  , REG_DATE DATE DEFAULT SYSDATE
  
   , CONSTRAINT FK_ACTIVITY_TEACHER_ID FOREIGN KEY (TEACHER_ID)
    REFERENCES TEACHER(ID) ON DELETE CASCADE
);

-- ACTIVITY 시퀀스 생성
CREATE SEQUENCE SEQ_ACTIVITY_NO nocache;
COMMIT;



