-- MEMBER 테이블 생성
CREATE TABLE MEMBER
(
    ID           VARCHAR2(20)	PRIMARY KEY
  , PASSWORD     VARCHAR2(20)	
  , NAME         VARCHAR2(20)	NOT NULL
  , BIRTH_DATE   DATE 			NOT NULL
  , PHONE        VARCHAR2(12)	NOT NULL
  , POST         CHAR(6)		NOT NULL 
  , BASIC_ADDR   VARCHAR2(200)	NOT NULL
  , DETAIL_ADDR	 VARCHAR2(200)	NOT NULL
  , EMAIL		 VARCHAR2(100)	NOT NULL UNIQUE
  , REG_DATE	 DATE			DEFAULT SYSDATE
  , GRADE		 CHAR(1)		DEFAULT 'B' --'B', 'S', 'G' , 'P'
  , OAUTH		 CHAR(1)
  , ADMIN		 CHAR(1)
);

-- BREED 테이블 생성
CREATE TABLE BREED
(
    NO          NUMBER(10)	 PRIMARY KEY
  , DOG_SIZE        CHAR(1)		 NOT NULL -- 'S', 'M', 'L'
  , BREED_NAME  VARCHAR2(20) NOT NULL
);

-- BREED SEQ 생성
CREATE SEQUENCE SEQ_BREED_NO nocache;
-- DOG 테이블 생성
CREATE TABLE T_DOG
(
    NO          NUMBER(10)   PRIMARY KEY
  , MEMBER_ID   VARCHAR2(20) NOT NULL
  , NAME     	VARCHAR2(20) NOT NULL
  , BIRTH_DATE  DATE 		 NOT NULL
  , BREED_CODE  NUMBER(10)   NOT NULL
  
  , CONSTRAINT FK_DOG_MEMBER_ID FOREIGN KEY (MEMBER_ID)
    REFERENCES T_MEMBER(ID) ON DELETE CASCADE
  , CONSTRAINT FK_DOG_BREED_CODE FOREIGN KEY (BREED_CODE)
    REFERENCES T_BREED(NO) ON DELETE CASCADE
);
-- DOG SEQ 생성
CREATE SEQUENCE SEQ_DOG_NO nocache;



-- DB링크 생성
CREATE DATABASE LINK DOG_XE CONNECT TO dogworld identified BY "dog1234"
USING '(DESCRIPTION =
	(ADDRESS = (PROTOCOL=TCP)(HOST=172.31.9.175)(PORT=1521))
	(CONNECT_DATA =
 		(SERVER = DEDICATED)
 		(SERVICE_NAME = XE)
	)
)';

-- DB링크 별칭 생성
CREATE synonym MEMBER FOR MEMBER@DOG_XE;
CREATE synonym BREED FOR BREED@DOG_XE;
CREATE synonym DOG FOR DOG@DOG_XE;

